name: Lab 1 - challengue 01

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: "Mensaje a mostrar"
        type: string
        required: true
  push:
    branches: 
      - master
    
jobs:
  job-read-input:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo input"
        run: |
          echo "Input recibido: ${{ inputs.mensaje }}"
  job-sequential:
    runs-on: ubuntu-latest
    steps:
      - name: Echo name step
        run: |
         echo "Job step: ${{ github.action }}" > /tmp/tmp.txt

      - name: Echo job
        run: |
         echo "Job : ${{ github.job }}"
  job-parallel:
    runs-on: ubuntu-latest
    steps:
      - name: Echo name step
        run: |
          echo "Job step: ${{ github.action }}"

  job-final:
    needs: [job-sequential,job-parallel]
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat /tmp/tmp.txt

