name: Hello Workflow


on:
  push:
    branches:
      - master


jobs:
    say_hello:
      name: "Show message Hello from workflow"
      runs-on: ubuntu-latest

      steps:
          - name: Show message
            run: echo "Hello Workflow, from the branch ${{github.ref.name}}"